### ISSUE TITLE
Breaks Sourcemaps?

### ISSUE THREAD

**Issue by developit** [egoist/rollup-plugin-postcss#1]
Hi - am I correct in assuming this plugin breaks sourceMaps?  It's doing a string transformation on the CSS file.  When I add this to my rollup plugin stack I get the following error:

```
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at decode (~proj/node_modules/rollup/www/ROLLUP/rollup/node_modules/sourcemap-codec/dist/sourcemap-codec.es6.js:100:22)
    at ~proj/node_modules/rollup/www/ROLLUP/rollup/src/utils/collapseSourcemaps.js:32:11
    at Array.map (native)
    at ~proj/node_modules/rollup/www/ROLLUP/rollup/src/utils/collapseSourcemaps.js:30:32
    at Array.map (native)
    at collapseSourcemaps (~proj/node_modules/rollup/www/ROLLUP/rollup/src/utils/collapseSourcemaps.js:29:25)
    at Bundle.render (~proj/node_modules/rollup/www/ROLLUP/rollup/src/Bundle.js:256:42)
    at Object.write (~proj/node_modules/rollup/www/ROLLUP/rollup/src/rollup.js:64:32)
    at ~proj/node_modules/rollup/bin/runRollup.js:116:18
    at tryCatch (~proj/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:182:12)
```

This is the offending `rollup.config.js`:

```js
import babel from 'rollup-plugin-babel';
import npm from 'rollup-plugin-npm';
import commonjs from 'rollup-plugin-commonjs';
import postcss from 'rollup-plugin-postcss';

export default {
    entry: 'src/index.js',
    dest: 'bundle.js',
    sourceMap: true,
    format: 'umd',
    plugins: [
        babel({ exclude: 'node_modules/**' }),
        npm({ jsnext: true, main: true }),
        commonjs(),
        postcss()
    ]
};
```

... note that reordering the plugins doesn't seem to help.

**Comment by egoist** [comment]
Thx for feedback, I just disabled generating source-map for Rollup to fix this. 

Since this plugin does not extract css into a single file, You can set PostCSS options `inline: true` to enable inline source-map when developing.

BTW, there should be 
```babel
babel({
  exclude: ['node_modules/**', '**/*.css'] 
})
```

// maybe there should be another plugin which extracts css into a single file for Rollup.

**Comment by developit** [comment]
@egoist I may have stumbled on the answer to why it's throwing:  the map returned from postcss is a JSON String, but rollup expects it to be an object.  Maybe adding a quick parse() would fix this?
The issue was noticed in the typescript plugin: https://github.com/rollup/rollup/issues/322

**Comment by egoist** [comment]
yep, you are right.

**Comment by developit** [comment]
Awesome, so happy to have this working! :D
