### ISSUE TITLE
[!] (postcss plugin) Error: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by und3f1ned** [egoist/rollup-plugin-postcss#110]
Hi! Error while importing LESS files. Which options? Where can I specify this options? Thanks.

**Comment by baurine** [comment]
> You can pass options to less by making use of the 'use' option:
> 
> ```
> postcss({
>       extensions: ['.css', '.scss', '.less'],
>       use : [
>         'sass', 
>         ['less', { javascriptEnabled: true }]
>       ],
>     }),
> ```

Works for me, thanks!

**Comment by asherccohen** [comment]
Anyone encountered an issue with this? I added this configuration but somehow the option is not sent to less.

**Comment by aprezcuba24** [comment]
How can I do the same using microbundle-crl? I'm working in a project but I don't see any configuration file.
