### ISSUE TITLE
Support cameCase option with postcss-modules

### ISSUE THREAD

**Issue by vwxyutarooo** [egoist/rollup-plugin-postcss#116]
The [`camelCase: true`](https://github.com/css-modules/postcss-modules#camel-cased-classes) option has added from [postcss-modules@1.2.0](https://github.com/css-modules/postcss-modules/blob/master/CHANGELOG.md#120), Please support this feature :pray:
I'm sure that'll be enough by just bump up the version. I could create PR If I may.

**Comment by zanona** [comment]
Should this also be supported by:

```js
postcss({
    modules: { localsConvention: 'camelCaseOnly' }
})
```
I tried it but had no effect?

**Comment by InsOpDe** [comment]
Worked for me

**Comment by kengreeff** [comment]
Same here for me, if I set:

```
postcss({
  extract: 'styles.css',
  modules: true,
  minimize: false,
  extensions: ['.sass', '.scss'],
  plugins: [
    postcssImport(),
    autoprefixer(),
  ],
  use: [
    ['sass', {
      includePaths: [
        './src/styles',
        './node_modules'
      ],
    }]
  ]
}),
```

Styles are built for modules:

```
.styles_search-bar__1WNEY input {
    width: 100%;
    margin-left: 16px;
    height: 24px;
    padding: 4px 0;
    font-size: 16px;
    border: 0;
    outline: none; }
```

If I change to:

```
postcss({
  extract: 'styles.css',
  modules: { localsConvention: 'camelCaseOnly' },
  minimize: false,
  extensions: ['.sass', '.scss'],
  plugins: [
    postcssImport(),
    autoprefixer(),
  ],
  use: [
    ['sass', {
      includePaths: [
        './src/styles',
        './node_modules'
      ],
    }]
  ]
}),
```

Styles are no longer built for modules:

```
.search-bar input {
    width: 100%;
    margin-left: 16px;
    height: 24px;
    padding: 4px 0;
    font-size: 16px;
    border: 0;
    outline: none; }
```

I'm probably missing something really basic here...

**Comment by kengreeff** [comment]
I think I figured it out.

You have to set `autoModules: false`, I think it is due to this code in the `postcss-loader.js` file:

```
const autoModules = options.autoModules !== false && options.onlyModules !== true
const isAutoModule = autoModules && isModuleFile(this.id)
const supportModules = autoModules ? isAutoModule : options.modules
```

If `options.autoModules` is undefined, `autoModules` is still true. If the file name doesn't isn't in the format `file.module.sass` then `isModuleFile` is false which means that `supportModules` is also `false`

Happy to create a PR to note this in the docs if required.

**Comment by 80666881** [comment]
> localsConvention

Thanks bro, It works for me! 
This problem just puzzled me whole day~👍
