### ISSUE TITLE
Upgrade cssnano to 4.x

### ISSUE THREAD

**Issue by nikolay-borzov** [egoist/rollup-plugin-postcss#121]
With cssnano 3.x there is an issue https://github.com/cssnano/cssnano/issues/588 (Comments aren't removed if browserlist contains Edge/UCAndroid)

**Comment by estrattonbailey** [comment]
+1 just ran into this as well. My issue is a deprecated method in a previous dep of `cssnano`, outlined [here](https://github.com/ben-eb/postcss-merge-rules/issues/52).

Updating to `cssnano@4.1.0` fixes my issue, but breaks the tests of this library (though for reference I see 2 tests failing even with this library in its current state).
