### ISSUE TITLE
Injected class names do not match CSS file

### ISSUE THREAD

**Issue by beccanelson** [egoist/rollup-plugin-postcss#129]
I am trying to create a library using typescript and the default `create-react-library` setup, which uses postcss with the `modules` flag to inject the styles into the head. I have a basic css file, which I am importing into `index.tsx`. When I build the project, however, the style names are getting jumbled, and the wrong names are getting injected into the documents' head.

`styles.css`:
```css
.o-grid-2-columns {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
}

.o-grid-3-columns {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
}
...etc
```

Compiled js:
```js
__$styleInject("._o-grid-2-columns_m2i85_1 {\n  display: grid;\n  grid-template-columns: repeat(2, 1fr);\n}\n\n._o-grid-3-columns_m2i85_6 {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr)...")
```

`rollup.config.js`:
```js
import typescript from "rollup-plugin-typescript2";
import commonjs from "rollup-plugin-commonjs";
import external from "rollup-plugin-peer-deps-external";
import postcss from "rollup-plugin-postcss-modules";
import resolve from "rollup-plugin-node-resolve";
import url from "rollup-plugin-url";
import sass from "rollup-plugin-sass";

import pkg from "./package.json";

export default {
  input: "src/index.tsx",
  output: [
    {
      file: pkg.main,
      format: "cjs",
      exports: "named",
      sourcemap: true
    },
    {
      file: pkg.module,
      format: "es",
      exports: "named",
      sourcemap: true
    }
  ],
  plugins: [
    external(),
    postcss({
      modules: true,
      writeDefinitions: true
    }),
    url(),
    resolve(),
    typescript({
      rollupCommonJSResolveHack: true
    }),
    commonjs()
  ]
};
```

If you want to see an example, I have created a basic library, and an example project that uses my library [here](https://codesandbox.io/s/lr2y4zw2vq). My components are not styled, because the class names in my React components don't match the class names in the head.

**Comment by beccanelson** [comment]
SORRY I figured this out. I didn't quite understand how to use the imported `styles` variable to access my classnames.

**Comment by lofiencier** [comment]
May i ask how did you figure it out?
I've met the same problem,
One jsx component with css file imported,worked perfectly with webpack,but with rollup,it didn't match the classname,it compiled just like this:
`var styles = { "_messeage_1vyb4_1": "index__messeage_1vyb4_1__2D5Cm" };
var cx = bind.bind(styles);

var Iiu = function (_React$Component) {
  inherits(Iiu, _React$Component);

  function Iiu(props) {
    classCallCheck(this, Iiu);
    return possibleConstructorReturn(this, (Iiu.__proto__ || Object.getPrototypeOf(Iiu)).call(this));
  }

  createClass(Iiu, [{
    key: 'render',
    value: function render() {
      return React.createElement(
        'div',
        { className: cx('message') },
        React.createElement(
          'p',
          null,
          'title'
        ),
        React.createElement(
          'span',
          null,
          '22222'
        )
      );
    }
  }]);
  return Iiu;
}(React.Component);
`

**Comment by nelhu** [comment]
> well...it seems like i'm using postcss({modules}) and using postcss-modules plugin in the same time,so it compiled and add hash twice.
> SO,sorry for bothering:)

thanks for your enlightened, I made the same mistake,  but still not know the theory of how rollup-postcss-plugin work
