### ISSUE TITLE
[Question] postcss.config.js support? EOM

### ISSUE THREAD

**Issue by QuantumInformation** [egoist/rollup-plugin-postcss#13]

**Comment by egoist** [comment]
We can use https://github.com/michael-ciniawsky/postcss-load-config , PR welcome.

**Comment by egoist** [comment]
It's supported in `v1.0`

**Comment by francoisromain** [comment]
@egoist Thank you !
🙏

**Comment by francoisromain** [comment]
Is it possible to load the config from package.json?

**Comment by egoist** [comment]
sure, any thing that `postcss-load-config` supports.

**Comment by francoisromain** [comment]
I updated from v. 0.5.6 to 1.0.1 (in this project: https://github.com/francoisromain/camomile-ui/blob/master/build/rollup.config.dist.js)

The postcss config is imported correctly from package.json. 

With the previous version, I had all the css extracted in a single `dist/styles.css` file (from vue templates and from the main css file imported in js). 

With version 1, `/dist/styles.css` only contains css from the vue templates. The css imported in the main js file is extracted in its own css file named after the exported js file (`my-project.common.css`), which is not what I want.

my rollup config was like: 
```
vue({
        compileTemplate: true,
        css: '../dist/styles.css'
      }),
      postcss({
        plugins: postcssPlugins,
        extract: '../dist/styles.css'
      }),
```

and now 
```
      vue({
        compileTemplate: true,
        css: '../dist/styles.css'
      }),
      postcss({
        extract: '../dist/styles.css'
      }),
```

What is the config to export all the css in a single file?
Thank you

**Comment by francoisromain** [comment]
I opened an issue about this last question: https://github.com/egoist/rollup-plugin-postcss/issues/59
