### ISSUE TITLE
How to get CSS output?

### ISSUE THREAD

**Issue by Shyam-Chen** [egoist/rollup-plugin-postcss#14]
```js
// vendor.js
import 'material-design-lite/dist/material.indigo-pink.min.css';
import 'material-design-lite/material';
```

Cordova build problem...

**Comment by egoist** [comment]
You mean extracting CSS? here's a PR working on this https://github.com/egoist/rollup-plugin-postcss/pull/11

**Comment by Shyam-Chen** [comment]
such as...

```js
// vendor.js

// css
import 'material-design-lite/dist/material.indigo-pink.min.css';

// js
import 'material-design-lite/material';
import 'firebase/firebase';
```

yielding

`vendor.css` and `vendor.js`

**Comment by meszaros-lajos-gyorgy** [comment]
You can use https://www.npmjs.com/package/rollup-plugin-postcss-export which has the same syntax as this plugin, but has an output parameter.

**Comment by Shyam-Chen** [comment]
I don't need, and has no further use Cordova.
