### ISSUE TITLE
Add support for "to" postcss option

### ISSUE THREAD

**Issue by sormy** [egoist/rollup-plugin-postcss#145]
Current version if this plugin has hardcoded "to" value to be the same as "from". This breaks a lot of postcss plugins that are relying on source/target filenames to properly rebase asset urls.

Example of affected plugin: https://github.com/sebastian-software/postcss-smart-asset

**Technically, any rebase plugin that is relying on `from` or `to` won't work as expected with currently hardcoded `from` and `to`.**

Would you be open to accept a small PR fix that will do this (so "to" could be explicitly passed when it is needed):

```diff
diff -ru rollup-plugin-postcss.old/dist/index.js rollup-plugin-postcss/dist/index.js
--- rollup-plugin-postcss.old/dist/index.js	2019-03-03 16:51:52.000000000 -0500
+++ rollup-plugin-postcss/dist/index.js	2019-03-03 17:01:25.000000000 -0500
@@ -185,7 +185,8 @@
       const postcssOpts = _objectSpread({}, _this.options.postcss, config.options, {
         // Followings are never modified by user config config
         from: _this.id,
-        to: _this.id,
+        // Allow overriding `to` for some plugins that are relying on this value
+        to: options.to || _this.id,
         map: _this.sourceMap ? shouldExtract ? {
           inline: false,
           annotation: false
@@ -669,6 +670,9 @@
     /** Postcss config file */
     config: inferOption(options.config, {}),
 
+    /** Postcss target filename hint, for plugins that are relying on it */
+    to: options.to,
+
     /** PostCSS options */
     postcss: {
       parser: options.parser,
```

**Comment by sormy** [comment]
Ping!

**Comment by sormy** [comment]
This issues is still actual even for newer version of this plugin. The fix is small, backward compatible and will improve support for other postcss plugin. Please let me know if you are ok with proposed approach and I will created PR with this change. Thank tou.

**Comment by sormy** [comment]
Ping!

**Comment by sormy** [comment]
Here is a PR for this change: https://github.com/egoist/rollup-plugin-postcss/pull/163

**Comment by ziofat** [comment]
postcss-url is also affected by this issue. 
I am trying to use background images in css but rollup will not pack them. 
I followed #118 to use postcss-url. However, I don't want to use base64 if the image is big. but the option 'rebase' is not working.
