### ISSUE TITLE
How to use sass instead of node-sass？

### ISSUE THREAD

**Issue by evecalm** [egoist/rollup-plugin-postcss#146]
- node-sass <https://github.com/sass/node-sass> written in C++, may need node-gyp to compile sometimes(and could be failed on some machine if some C++ compiling dependencies are missing)
- sass <https://github.com/sass/dart-sass> written in dart introduced by sass officially, no need to compile when installing.

**Comment by egoist** [comment]
👌🏻 Supported in 2.0.0, `node-sass` still takes priority though.

**Comment by samthor** [comment]
drive-by comment: [dart-sass](https://www.npmjs.com/package/dart-sass) and [sass](https://www.npmjs.com/package/sass) is the same code, published twice.

As of 2.0.3, this plugin will only look for "sass".

**Comment by doesdev** [comment]
Another drive-by comment, this is not true. Or at least, for me it seems. Had an absolute phantom, everything stopped building. Built yesterday and today it didn't. Won't bog down with details but for the sake of future Googlers the error is below and the only thing that worked for me was switching back `node-sass`. Had been using `sass` for many months. Who knows.

```
[!] (plugin postcss) CssSyntaxError: C:\Users\andrew.carpenter\repos\wcmd-webui\app\styles
\app.sass:636:22: Missed semicolon
You tried to parse Sass with the standard CSS parser; try again with the postcss-sass pars
er
```
