### ISSUE TITLE
Compatibility with rollup-plugin-vue

### ISSUE THREAD

**Issue by znck** [egoist/rollup-plugin-postcss#149]
`rollup-plugin-vue` add a query param to `id` to import style blocks from `.vue` file but query params are stripped here: https://github.com/egoist/rollup-plugin-postcss/blob/6d1ec84ae51b56b392f73807d4dfb541939ca0ef/src/index.js#L96-L100

ID pattern: `Foo.vue?rollup-plugin-vue=styles.[index].[lang]`
Example: `Foo.vue?rollup-plugin-vue=styles.0.css`

**Comment by egoist** [comment]
that's already removed in the latest version
