### ISSUE TITLE
scss modules doesn't work 

### ISSUE THREAD

**Issue by daniele-zurico** [egoist/rollup-plugin-postcss#167]
Hi all,
I just create a library with create-react-library and it works really well. However, I was looking to add scss support but when I rename in scss it raise an error.
These are the step I did:

npm install node-sass --dev
("node-sass": "^4.12.0")
src/helloWorld
HelloWorld.module.scss
HelloWorld.tsx:
`import styles from './HelloWorld.module.scss';`
When I run npm start:
```
[!] (rpt2 plugin) Error: /Users/daniele/Documents/Projects/capgemini-conception/react-library/src/helloWorld/HelloWorld.tsx(2,20): semantic error TS2307 Cannot find module './HelloWorld.module.scss'.
```
I missed something?

**Comment by SASUKE40** [comment]
It fixed.
