### ISSUE TITLE
~ and custom alias support for less

### ISSUE THREAD

**Issue by fieldju** [egoist/rollup-plugin-postcss#170]
I needed support for ~ and other webpack style aliases that the webpack less-loader supports so I made one for `rollup-plugin-postcss`

https://github.com/fieldju/rollup-plugin-postcss-webpack-alias-less-loader

I am hoping we can link to it in the readme for the next poor soul that needs '~' with rollup / postcss.

in use: https://github.com/fieldju/deck/blob/feature/publish_es_module/app/scripts/modules/core/rollup.config.js#L42

**Comment by dosentmatter** [comment]
@fieldju, thanks for your work. I will try it out.

The link is out of date. Here is one linking to specific commit hash: https://github.com/fieldju/deck/blob/25d7fa099a4a40fc7c53f12f27fca03f99ed49cb/app/scripts/modules/core/rollup.config.js#L106-L113

@egoist, added support for sass in #77. Perhaps we can move the less logic in rollup-plugin-postcss-webpack-alias-less-loader into rollup-plugin-postcss.

**Comment by Himself65** [comment]
this bug should be fixed after #77
