### ISSUE TITLE
Q: how to pass custom options to the sass loader

### ISSUE THREAD

**Issue by krvajal** [egoist/rollup-plugin-postcss#187]
I need to pass custom options to the `node-sass` loader. Is it possible to achieve it?
Specifically, I want to define custom functions as explained here.
https://github.com/sass/node-sass/blob/master/README.md#functions--v300---experimental.

I know I can define functions with postcss but I need them to execute earlier, when the sass processing is happening.

**Comment by calledT** [comment]
The [use](https://github.com/egoist/rollup-plugin-postcss#use) options allow you config loader's options. 

example
```js
// rollup.config.js
import postcss from 'rollup-plugin-postcss';
import jsonImporter from 'node-sass-json-importer';

export default {
  ...
  plugins: [
    postcss:({ use: [['sass', { importer: [jsonImporter] }]] })
  ]
};
```

**Comment by krvajal** [comment]
Thx, works nicely
