### ISSUE TITLE
Consider adding postcss-modules integration

### ISSUE THREAD

**Issue by just-boris** [egoist/rollup-plugin-postcss#2]
Now CSS-files returns nothing on export. But it would be good to export class names map like Webpack does with `css-modules` enabled.

There is a [postcss-modules](https://github.com/outpunk/postcss-modules) plugin that gives CSS-modules feature support for postcss. It emits JSON with class names mapping and it can be used as actual export. So, the generated output will look like:

```js
__$styleInject('.a {color:red;}.b {color:blue;}');

export default {
    'a': '_a_16zx1_1',
    'b': '_b_16zx1_2'
};
```

What do you think about it? If you interested in this feature, I can contribute and send a pull-request.

**Comment by egoist** [comment]
Sure I like this feature, glad that you can make a pull-request! Do it!

**Comment by piuccio** [comment]
This would be amazing @just-boris did you manage to get a branch running?

**Comment by just-boris** [comment]
No, I didn't. I solved my specific issue in another way.

Maybe eventually I will do it, but not so soon.

**Comment by egoist** [comment]
Thank to @piuccio 's work, a new version with postcss-modules support was published 🎉
