### ISSUE TITLE
CI build failed on node-sass

### ISSUE THREAD

**Issue by Himself65** [egoist/rollup-plugin-postcss#219]
https://github.com/egoist/rollup-plugin-postcss/pull/216
https://github.com/egoist/rollup-plugin-postcss/pull/215
https://github.com/egoist/rollup-plugin-postcss/pull/214
https://github.com/egoist/rollup-plugin-postcss/pull/213
...

**Comment by egoist** [comment]
we need to rebase those branches, node-sass has been updated in master branch for node 12 support
