### ISSUE TITLE
node-sass error

### ISSUE THREAD

**Issue by FFxSquall** [egoist/rollup-plugin-postcss#223]
Release 2.0.4 #211 broke using sass dart.
```
  "devDependencies": {
    "rollup-plugin-postcss": "^2.0.4",
    "sass": "^1.24.4"
```
build error:
```
[!] (plugin postcss) Error: Cannot find module 'node-sass'
src/styles/common.scss
Error: Cannot find module 'node-sass'

```

**Comment by jpa00** [comment]
loadModules's require.resolve() call should be wrapped in a try-catch. Otherwise it throws if you only have dart sass installed. This currently prevents using 2.0.4 for me.
