### ISSUE TITLE
3.1.0 Extract gives empty file

### ISSUE THREAD

**Issue by atompkins** [egoist/rollup-plugin-postcss#271]
rollup 2.7.2
plugins: [postcssNesting(), cssnano()]

**Comment by BogdanDarius** [comment]
rollup-plugin-postcss 3.0.0 seems to work, must be something introduced in 3.1.0.

**Comment by BogdanDarius** [comment]
It is something introduced in 3.1.0.
It was pointed **https://github.com/egoist/rollup-plugin-postcss/pull/264#issuecomment-618574076**

**Comment by SASUKE40** [comment]
Could you give some minimal example?

**Comment by daviddelusenet** [comment]
Experiencing the same issue.

Config:

```tsx
postcss({
    extract: true,
    minimize: true,
    plugins: [
        // Drops the preceeding '~' (needed for Storybook webpack loaders) &
        // removes intermediate dirs from font imports
        postcssUrl({
            filter: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
            url: (asset) => `fonts/${asset.url.substr(1).split('/').pop()}`,
        }),
    ],
}),
```

My only CSS imports:

```tsx
import '../app/styles/fonts/exo2/exo2.css';
import '../app/styles/fonts/iconfont/iconfont.css';
import '../app/styles/fonts/opensans/opensans.css';
```

**Comment by SASUKE40** [comment]
> It is something introduced in 3.1.0.
> It was pointed **[#264 (comment)](https://github.com/egoist/rollup-plugin-postcss/pull/264#issuecomment-618574076)**

@atompkins @BogdanDarius @daviddelusenet 
Reverted, use `v3.1.1`.
