### ISSUE TITLE
Use css modules and cssnext

### ISSUE THREAD

**Issue by jarben** [egoist/rollup-plugin-postcss#29]
Not sure what I'm doing wrong but using css modules and cssnext doesn't seem to work, here is my setup: 

![image](https://user-images.githubusercontent.com/561365/27227316-5260d200-52a3-11e7-87ba-6ca96fd6f2ff.png)

 Any thoughts?

**Comment by lmihaidaniel** [comment]
Can you send us the full rollup related code used in your config ?

**Comment by jarben** [comment]
Sorry @lmihaidaniel , just found out that there is a limitation to the :root selector in cssnext, this was causing the issue as I was creating variables in a different scope. 

![image](https://user-images.githubusercontent.com/561365/27626983-66ae5cb4-5bea-11e7-89f7-c4336fe1b1ea.png)

Thanks for looking at this and sorry again.

**Comment by lmihaidaniel** [comment]
Thx @jarben for the feedback
