### ISSUE TITLE
Add syntaxes/parsers

### ISSUE THREAD

**Issue by NicolasParada** [egoist/rollup-plugin-postcss#3]
There is a limitation for not allowing the `parser` or `syntax` options?
Or there is a way I'm not seeing... I've tried:
```js
postcss({
  plugins: [],
  options: {
    parser: sugarss
  }
})
```
and:
```js
postcss({
  plugins: [],
  parser: sugarss
})
```
And either works.

**Comment by egoist** [comment]
It should work with the latest version `^0.1.1` now, just pass `parser` options to postcss like:

```js
postcss({
  plugins: [],
  parser: sugarss
})
```

**Comment by NicolasParada** [comment]
Yeah, is working now. I was about to do the PR now... Thanks :)
