### ISSUE TITLE
TS definitions for namedExports does not match the docs

### ISSUE THREAD

**Issue by AndrewLeedham** [egoist/rollup-plugin-postcss#303]
[According to the docs](https://github.com/egoist/rollup-plugin-postcss#namedexports) it should either be a boolean or a function which transforms a string, however the [current definitions](https://github.com/egoist/rollup-plugin-postcss/blob/7ce64155ed0ff37151f6280c6740472d2571f193/types/index.d.ts#L24) specify a function which returns a boolean.

**Comment by AndrewLeedham** [comment]
Looks like there is already a PR for this: https://github.com/egoist/rollup-plugin-postcss/pull/302

**Comment by rmedaer** [comment]
PR #302 merged. [Release v3.1.5](https://github.com/egoist/rollup-plugin-postcss/releases/tag/v3.1.5)
