### ISSUE TITLE
Accessing "this.moduleIds" on the plugin context by plugin postcss is deprecated.

### ISSUE THREAD

**Issue by wuquanyao** [egoist/rollup-plugin-postcss#313]
Error: Accessing "this.moduleIds" on the plugin context by plugin postcss is deprecated. The "this.getModuleIds" plugin context function should be used instead.

Rollup Deprecated Context Functions

![image](https://user-images.githubusercontent.com/13231421/90947153-27938d80-e466-11ea-9fd2-bd49dc1b3e9c.png)

pollup-plugin-postcss

![image](https://user-images.githubusercontent.com/13231421/90947124-fb780c80-e465-11ea-97a9-74c3c392f9d5.png)

**Comment by wardpeet** [comment]
We need to make sure that we keep backwards compatability so we should check if this.getModuleIds is present or not.

We would love a PR for this! 👍 

Thank you for creating this issue.

**Comment by wardpeet** [comment]
Moduleids has been removed in favor of a different technique in #295. Closing this because it's fixed in the latest release.
