### ISSUE TITLE
PostCSS 8

### ISSUE THREAD

**Issue by ai** [egoist/rollup-plugin-postcss#324]
PostCSS 8 was released. It has no breaking changes related to `rollup-plugin-postcss`, most of changes are for plugins. [Full changelog](https://github.com/postcss/postcss/releases/tag/8.0.0).

- [ ] Move `postcss` to `peerDependencies`
- [ ] Update `postcss` version

**Comment by ai** [comment]
We also will need to update `postcss-load-config` to 3.0

**Comment by isaacl** [comment]
This is starting to become a real thorn with other dependencies. Is it just simple dependency upgrades?

**Comment by ai** [comment]
1. Update `postcss` and `postcss-load-config`
2. Move `postcss` to `peerDependencies` to allow users update to the future PostCSS 9 without updating this plugin

PostCSS 8 supports all PostCSS 7 plugins and have 99,9% that same API for the case of this plugin.

**Comment by isaacl** [comment]
If you want to get this early, I pushed a fork:
```json
    "rollup-plugin-postcss": "https://github.com/isaacl/rollup-plugin-postcss"
```

**Comment by greven** [comment]
Is there any update on a release to fix this? This breaks for example using Tailwind 2.0 with rollup.

**Comment by camjackson** [comment]
Thanks @isaacl you're the best!

For those wanting to use the fork, you can add it as a dependency like this:

```
yarn add -D rollup-plugin-postcss@https://github.com/isaacl/rollup-plugin-postcss
```

For extra safety, you might like to pin it to a specific commit for which you have reviewed the diff from the original repo: 

```
yarn add -D rollup-plugin-postcss@https://github.com/isaacl/rollup-plugin-postcss#9095159
```

 I'm sure @isaacl isn't about to go and push a bitcoin miner to HEAD but you never know 😉

**Comment by ai** [comment]
Thanks. I updated [the migration guide](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users).
