### ISSUE TITLE
How do I simply minify 1 file?

### ISSUE THREAD

**Issue by 9mm** [egoist/rollup-plugin-postcss#326]
I feel like i'm going crazy doing this for hours... all I want to do is literally minify 1 single file for my library. I don't want modules, injection, or anything like that.

This is what I have so far and I'm getting `(!) The emitted file "reset.css" overwrites a previously emitted file of the same name.`

```
  {
    input: 'assets/reset.css',
    plugins: [
      postcss({
        extract: true,
        sourceMap: false,
        minimize: true,
        plugins: [],
      }),
    ],
    output: {
      file: 'dist/reset.css',
    },
  },
```

**Comment by FredZeng** [comment]
{
  input: 'assets/reset.css',
  plugins: [
    postcss({
      extract: 'dist/reset.css',
      sourceMap: false,
      minimize: true,
      plugins: [],
    }),
  ],
  output: {
    file: 'dist/reset.js',
  },
},

**Comment by FredZeng** [comment]
It's more appropriate to change `file: 'dist/reset.css'` => `file: 'dist/reset.js'`, since `rollup` eventually outputs JS bundles. See [extract](https://github.com/egoist/rollup-plugin-postcss#extract), `extract: true` will extract CSS to the same location where JS file is generated. In your case, the output JS file was named `dist/reset.css`, which would conflict with the CSS file extracted by the plugin.

**Comment by 9mm** [comment]
Hmm... I think i see... but what if my CSS has nothing to do with my JS?

I'm compiling 2 files:

* `iframe.js` -> `dist/iframe.min.js`
* `load.js` -> `dist/load.min.js`
* `reset.css` -> `dist/reset.min.css`.

```javascript
export default [
  {
    input: 'assets/reset.css',
    plugins: [
      postcss({
        extract: true,
        modules: false,
        sourceMap: false,
        plugins: [
          require('cssnano')({
            preset: 'default',
          }),
        ],
      }),
    ],
    output: {
      file: 'dist/reset.js',
    },
  },
  {
    input: 'src/load.js',
    plugins,
    output: {
      file: 'dist/load.min.js',
      format: 'iife',
      sourcemap: false,
    },
  },
  {
    input: 'src/iframe.js',
    plugins,
    output: {
      file: 'dist/iframe.min.js',
      format: 'iife',
      sourcemap: false,
    },
  },
];
```

**Comment by FredZeng** [comment]
just ignore that warning since u know what ur doing, or u can custom handle the warning.

```
{
    input: 'assets/reset.css',
    plugins: [
      postcss({
        extract: true,
        modules: false,
        sourceMap: false,
        plugins: [
          require('cssnano')({
            preset: 'default',
          }),
        ],
      }),
    ],
    output: {
      file: 'dist/reset.css',
    },
    onwarn(warning, warn) {
      if (warning.code === 'FILE_NAME_CONFLICT') return
      warn(warning)
    }
  },
```

**Comment by 9mm** [comment]
Ahhh ok. Thanks! It's weird rollup can't just do something simple, I encounter the same thing with webpack. These systems are so immensely advanced and yet... minifying a single file appears to be out of the question.
