### ISSUE TITLE
how to add custom header banner 

### ISSUE THREAD

**Issue by lhlyu** [egoist/rollup-plugin-postcss#338]
/*
    @name: ${pk.name}
    @description: ${pk.description}
    @repository: ${pk.repository}
    @author: ${pk.author}
    @version: ${pk.version}
    @time: ${new Date().toLocaleString()}
 */

I want to add the above banner to css, how to write?

```js
postcss({
       extract: 'bundle.css',
       minimize: true,
       plugins: [
              autoprefixer
       ]
 })
```

 `postcss-banner` is not work

**Comment by SASUKE40** [comment]
Could you offer a minimal scenario for testing?

**Comment by lhlyu** [comment]
I have resolved.

**Comment by imaginarny** [comment]
How have you solved this @lhlyu? 

I used the `postcss-header` plugin, but it would be nice to know if it's possible without.  It's not perfect though, there's missing new line right after, on minimize. 

There could be support for Rollup `output.banner` option out-of-the-box.

**Comment by lhlyu** [comment]
@imaginarny 
Sorry, it's been too long and I forgot. It should be a third-party plugin.
