### ISSUE TITLE
postcss.plugin was deprecated. Migration guide

### ISSUE THREAD

**Issue by tvvignesh** [egoist/rollup-plugin-postcss#350]
Hi. I recently upgraded to `"postcss": "8.2.1"` with `"rollup-plugin-postcss": "^4.0.0"` and I see that I get a lot of warnings like this when `minimize` is set to true:

```ts
postcss({
	minimize: true
})
```

<img width="248" alt="1" src="https://user-images.githubusercontent.com/1165845/103057922-db4c8b80-45c6-11eb-9d88-242963178aae.PNG">

And eventually creates errors in the CSS files:

<img width="434" alt="2" src="https://user-images.githubusercontent.com/1165845/103057975-f9b28700-45c6-11eb-9bc9-88ffc6bf27bb.PNG">

But if I don't add `minimize` I do not get these warnings, nor does anything fail.

Thanks.

**Comment by litt1e-p** [comment]
the same +1

**Comment by ludofischer** [comment]
I think removing `minimize` fixes the warning because the `minimize` option activates cssnano, and the current cssnano uses the old PostCSS API.

**Comment by andykenward** [comment]
Even without `minimize` I am getting this error. :(
