### ISSUE TITLE
scss modules doesn't work

### ISSUE THREAD

**Issue by FreakyHarsh** [egoist/rollup-plugin-postcss#377]
I'm trying to use **scss modules** in my project with this configuration:

```
postcss({
        modules: true,    
        extract: true,  
        use: ["sass"], 
        writeDefinitions: true
      }), 

```
This does not work. But if I use **css module** it will work fine.

I'm using 
```
"rollup-plugin-postcss": "^4.0.0",
"postcss": "^8.3.0",
"node-sass": "^6.0.0",
```
I found someone with same issue but didn't found the solution there
#167

**Comment by FreakyHarsh** [comment]
> I'm trying to use **scss modules** in my project with this configuration:
> 
> ```
> postcss({
>         modules: true,    
>         extract: true,  
>         use: ["sass"], 
>         writeDefinitions: true
>       }), 
> ```
> 
> This does not work. But if I use **css module** it will work fine.
> 
> I'm using
> 
> ```
> "rollup-plugin-postcss": "^4.0.0",
> "postcss": "^8.3.0",
> "node-sass": "^6.0.0",
> ```
> 
> I found someone with same issue but didn't found the solution there
> #167


My issue was solved using this 
```
postcss({
      modules: true,
      inject: true,
      // extract: true, // uncomment if you want separate css file
      // minimize: true,
      use: [
        [
          "sass",
          {
            includePaths: ["./src/styles", "./node_modules"]
          },
          [
            "less",
            {
              javascriptEnabled: true
              // modifyVars: themeVariables
            }
          ]
        ]
      ]
    }),
```

**Comment by qiutian00** [comment]
```
postcss({
      modules: true,
      inject: true,
      // extract: true, // uncomment if you want separate css file
      // minimize: true,
      use: [
        [
          "sass",
          {
            includePaths: ["./src/styles", "./node_modules"]
          },
        ]
      ]
    }),
```

Good, This works for me
