### ISSUE TITLE
[Question] Process and extract CSS but leave an `import` statement

### ISSUE THREAD

**Issue by tuxsudo** [egoist/rollup-plugin-postcss#39]
Suppose I have the following source files:

```
// src/Add.js 
import React from 'react';
import styles from './Add.css';
export const Add = () => <span className={styles.Add}>+</span>
```

And a corresponding css file (that needs to be post-processed with postcss with cssnext):

```
// src/Add.css
.Add {
  color: red;

  &:hover {
    color: blue;
  }
}
```

My current rollup config looks like:

```
{
//...
  plugins: [
    postcss({
      sourceMap: true,
      extract: true,
      plugins: [
        cssImport(),
        cssNext(),
        postcssModules({
          getJSON(id, exportTokens) {
            cssExportMap[id] = exportTokens;
          }
        })
      ],
      getExport(id) {
        return cssExportMap[id];
      },
      getExportNamed: false,
      extensions: [".css"]
    }),
    babel({
      babelrc: false,
      presets: [require.resolve("babel-preset-react-app")]
    })
  ]
}
```

Which, when ran, creates two _dist_ files, this js file:

```
// dist/Add.js
import React from 'react';

var styles = { "Add": "_Add_1kcg1_1" };

var Add = function Add() {
  return React.createElement(
    'span',
    { className: styles.Add },
    '+'
  );
};

export { Add };
```

and this css file: 

```
// dist/Add.css
._Add_1kcg1_1 {
  color: red
}
._Add_1kcg1_1:hover {
  color: blue;
}
```

This is almost exactly what I want, but in an effort to make this `Add` component easier for apps to consume (like create-react-apps without ejecting), I'd like for the `dist/Add.js` to _reference_ the processed `dist/Add.css` file, eg:

```
// desired dist/Add.js
import React from 'react';
import './Add.css'; // <-- this is what I want added

var styles = { "Add": "_Add_1kcg1_1" };

var Add = function Add() {
  return React.createElement(
    'span',
    { className: styles.Add },
    '+'
  );
};

export { Add };
```

Otherwise, apps consuming this `Add` component would need to import both the js and css file, which I'm trying to avoid.

So 3 questions:

1. Am I making sense?  😬 
2. Is this possible?
3. If so, how?

**Comment by lmihaidaniel** [comment]
So basically you want to have the following behavior :
```
import styles from './Add.css';
```
and
```
import './Add.css';
```
to behave in the same way by providing the object `styles` to where the css file is imported ?

If this is what you are looking for, what will happen when you have something like this:
```
import './Add.css';
import './AddB.css';
import styles from './AddC.css';
```

I think this is out of the scope.

**Comment by lmihaidaniel** [comment]
Sorry for my last reply, now i understand what actually you need. Will investigate if it is possible and what are the implications of doing that.

**Comment by egoist** [comment]
> apps consuming this Add component would need to import both the js and css file, 

This is actually the preferred way 😅 

Anyways this is out of the scope of this project, you can use a rollup plugin to inject some code the the top if you really need this.
