### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by bryanjtc** [egoist/rollup-plugin-postcss#418]
I'm using aliases on my scss modules and postcss can't file the stylesheet to import. Any recomendations on how to fix this? I currently use @rollup/plugin-alias to resolve aliases on all my files, but it doesn't work on scss files.
```
[!] (plugin postcss) Error: Can't find stylesheet to import.
  ╷
1 │ @use '@typography' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

**Comment by zjjjjjjjjjjd** [comment]
same problem

**Comment by madmadi** [comment]
I added SCSS config alongside with rollup alias, and that worked for me:

```js
{
  ...
  plugins: [
    alias({
      entries: [
        { find: 'components', replacement: path.resolve(__dirname, './src/components') },
      ],
    }),
    postcss({
      use: {
        sass: {
          includePaths: [
            path.resolve(__dirname, './src'),
          ],
        },
      },
    }),
  ],
};
```

**Comment by bryanjtc** [comment]
@madmadi I confirm that your solution works on my project.
