### ISSUE TITLE
extract: true broken

### ISSUE THREAD

**Issue by flying-sheep** [egoist/rollup-plugin-postcss#43]
when used via `rollup.config.js`, rollup now provides `options.file` instead of `options.dest`.

**Comment by lmihaidaniel** [comment]
Fixed by #44

**Comment by meszaros-lajos-gyorgy** [comment]
When will this be published to NPM? I tried installing the module through this link:
github:egoist/rollup-plugin-postcss#0.5.5
But it misses some files, which I assume gets compiled just before publishing.
