### ISSUE TITLE
0.5.5 is not published

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [egoist/rollup-plugin-postcss#48]
I see, that 0.5.5 was released 6 days ago, but it's not yet been published. I've tried adding it to my repo through "github:egoist/rollup-plugin-postcss#0.5.5", but it is missing some files, so I assume, that publishing requires some additional building.

Can you please publish it?

**Comment by egoist** [comment]
@lmihaidaniel what's your npm username? I'd like to add you on npm too

**Comment by lmihaidaniel** [comment]
`lmihaidaniel`
https://www.npmjs.com/~lmihaidaniel

**Comment by egoist** [comment]
Added, and `v0.5.5` is published.

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!
