### ISSUE TITLE
Update style-inject

### ISSUE THREAD

**Issue by egoist** [egoist/rollup-plugin-postcss#53]
I have removed `returnValue` in style-inject [v0.2.0](https://github.com/egoist/style-inject/releases/tag/v0.2.0), it should be handled here instead. eg:

https://github.com/egoist/rollup-plugin-postcss/blob/9cea5b0e89781db5876accab02e3e39304e55681/src/index.js#L176-L178

we should not export the return value of `styleInject()` but the actual `codeExportDefault` directly.

**Comment by lmihaidaniel** [comment]
update provided by #55
