### ISSUE TITLE
how to use with rollup-plugin-vue and export a single css file?

### ISSUE THREAD

**Issue by francoisromain** [egoist/rollup-plugin-postcss#59]
I updated from v. 0.5.6 to 1.0.1 (in this project: https://github.com/francoisromain/camomile-ui/blob/master/build/rollup.config.dist.js)

In this project there are two sources of css: 
- a main css file is imported in `app.js` with `import './css/styles.css'`
- many components css in the vue files.

With the previous version of `rollup-plugin-postcss`, I had all the css extracted in a single dist/styles.css file (from vue templates and from the styles.css).

With version 1, /dist/styles.css only contains css from the vue templates. The css imported in the main js file is extracted in its own css file named after the exported js file (/dist/my-project.common.css), which is not what I want.

my rollup config with v0.5.6:

```
vue({
        compileTemplate: true,
        css: '../dist/styles.css'
      }),
      postcss({
        plugins: postcssPlugins,
        extract: '../dist/styles.css'
      }),
```

and now with v.1.0.1

```
      vue({
        compileTemplate: true,
        css: '../dist/styles.css'
      }),
      postcss({
        extract: '../dist/styles.css'
      }),
```

What is the config to export all the css in a single file?
Thank you

**Comment by egoist** [comment]
Can you do `<style src="./style.css"></style>`?

**Comment by egoist** [comment]
Well this is not possible for two plugins to write to the same file since they use different ways to extract css, you can manually merge the two output files though.

**Comment by francoisromain** [comment]
ok. 
- do you have a suggestion of the tool to merge the files? 
- how is it possible to name the css file extracted with rollup-plugin-postcss? (this `extract: '../dist/styles.css'` has no incidence)

**Comment by egoist** [comment]
does not support naming for now 😅 will add that soon.

**Comment by francoisromain** [comment]
Ok. 
I don't understand what you mean by this feature: `<style src="./style.css"></style>` 

rollup-plugin-vue support extracting the css. Is it something else?

**Comment by egoist** [comment]
Have you tried vue-loader 😄 https://vue-loader.vuejs.org/en/start/spec.html#src-imports

**Comment by francoisromain** [comment]
Ok, now I see what you mean. 
This raise many more questions 😄 

- With webpack, I use the htmlwebpackplugin which generates the index.html with links to the css and js. Where this insertion feature of vue-loader comes in?
- I use rollup to bundle and publish on npm a vue component library. In this case, there is no index.html at all, so I don't need to insert a <link> tag. How should I publish the css in this case: external file, or bundle within the components?

Thank you very much

**Comment by egoist** [comment]
I'm not sure what you mean, the `src` attr is used to import css file in SFC.

Anyways this is out of the scope of this project.

**Comment by egoist** [comment]
Hi, actually I just found a solution, see https://vuejs.github.io/rollup-plugin-vue/#/en/2.3/?id=use-other-plugins

**Comment by francoisromain** [comment]
@egoist Thanks for letting me know. I will try that
