### ISSUE TITLE
unnamed requires breaks bundled code 

### ISSUE THREAD

**Issue by lafka** [egoist/rollup-plugin-postcss#6]
Sorry for undetailed issue, I'm still digging and learning about rollup and this es6 thing..

When using unnamed requires (i.e. [pivotal-ui's typography](https://github.com/pivotal-cf/pivotal-ui/blob/480e00ca294a0c87c3bed29bf17a3b6b8c772e84/library/src/pivotal-ui/components/lists/index.js)) the plugin does not add expected(?) variable.

Example of some generated code, where `__$styleInject`  does not add the variable name but the caller expects `var typography` to be available.

``` javascript
__$styleInject("@font-face{font-...", undefined);

var typography$1 = Object.freeze({
    default: typography
});
```

Adding a `var typography = require('./typography.css');` fixes the issue.

Due to my lack of knowledge of rollup i'm not sure if `require` should automatically prepend the basename as a variable, it might cause some weird naming collisions...

Doing something like

``` javascript
const varname = path.basename(id, path.extname(id))
const code = `var ${varname} = ${injectFnName}(${JSON.stringify(result.css)},${JSON.stringify(getExport(result.opts.from))});\nexport default ${varname};`;
```

resolves the issue, but again i'm not sure if this is a problem with the library in question, this library or rollup....

Let me know what you think is the best option to resolve this!

**Comment by egoist** [comment]
Why do you want to assign the return value (undefined) to a variable?

**Comment by lafka** [comment]
This was just examples from the generated code, the variable assignment resolved the issue for me.
Don't remember the exact details but exporting the (possibly empty) name seemed to trigger some magic reaction.

This might have been fixed since then,  i'm not using this pivotal/rollup in combination so i have no way to check. You can close if you feel like it.
