### ISSUE TITLE
Latest published version does not write extracted CSS files

### ISSUE THREAD

**Issue by jsanchez034** [egoist/rollup-plugin-postcss#63]
The latest version does not write out css files if `extract` option is passed. Also looks like the `dist` folder has two files in it...
![image](https://user-images.githubusercontent.com/761087/35356982-0f6c3472-0120-11e8-802a-96ccf9ca7949.png)
The file `index.cjs.js` has stale code in it too. Is this maybe related to the bili update..
https://github.com/egoist/rollup-plugin-postcss/commit/0fe23ad?

**Comment by jsanchez034** [comment]
Did a compare on the `1.2.5` and `1.2.6` bundles and looks like these lines are causing the issue..
![image](https://user-images.githubusercontent.com/761087/35358078-754d800e-0123-11e8-970f-8b38ed992a35.png)
`extracted` variable is a `Map` data structure not an Array so `extracted.values()` is of type `Iterator` not Array as well but the loop in the above is trying to access `extracted.values()` using Array bracket notation. So the issue has something to do with `bili` dependency I believe.

**Comment by egoist** [comment]
This https://github.com/egoist/rollup-plugin-postcss/commit/0fe23ad actually fixed it but I forgot to run `yarn` again in my home computer when publish 😅

**Comment by egoist** [comment]
fixed in `v1.2.7`

**Comment by jsanchez034** [comment]
No worries, thank you!
