### ISSUE TITLE
Add SugarCSS loader or how to append it?

### ISSUE THREAD

**Issue by olstenlarck** [egoist/rollup-plugin-postcss#67]
Heya @egoist! :tada: 

This rollup plugin seems amazing! So much things.. :D I can't believe.
So, i like that it support SASS/SCSS, LESS, Stylus, but i'm wondering how to add SugarCSS to be used on `.sss` and/or `.css`?

**Comment by olstenlarck** [comment]
Oh.. I got it ;d

like that

```js
postcss({
  use: ['sass', 'stylus', 'less', 'sugarcss'],
  loaders: [
    {
      name: 'sugarcss',
      test: /\.[sc]ss$/,
      async process ({ code }) {},
    },
  ],
})
```

**Comment by olstenlarck** [comment]
Hm. Actually.. Still can't figure out how to do the things :D Just want `.css` to be processed normally, and `.sss` with the SugarCSS parser.

So when we have all the parsers installed to use each of them depending on the different extensions

**Comment by egoist** [comment]
Currently you can set https://github.com/egoist/rollup-plugin-postcss#parser to use sugarss, but as

https://github.com/egoist/rollup-plugin-postcss/blob/beef7c55a4f848a419693b9c91a723e661618e6c/src/postcss-loader.js#L51

the postcss-loader will also use it for `.css` file, we can fix that tho 😅

**Comment by egoist** [comment]
You can also use a postcss config file and dynamically set parser based on extention:

```js
// postcss.config.js
module.exports = ({ file }) => ({
  parser: file.extname === '.sss' ? 'sugarss' : false,
  plugins: {
    'postcss-import': { root: file.dirname },
    'postcss-cssnext': options.cssnext ? options.cssnext : false,
    'autoprefixer': env == 'production' ? options.autoprefixer : false,
	// ...
  }
})
```
