### ISSUE TITLE
invalid z-index after postcss with `minimize` option

### ISSUE THREAD

**Issue by bodia-uz** [egoist/rollup-plugin-postcss#73]
Given js file with imported `index.scss`:
https://github.com/bodia-uz/rollup-postcss-modules-test/blob/master/src/index.scss#L1-L4

`z-index` in the source file is `5`.

After postcss with `minimize` option `z-index` become `1`
https://github.com/bodia-uz/rollup-postcss-modules-test/blob/master/rollup.config.js#L8-L12

https://github.com/bodia-uz/rollup-postcss-modules-test/blob/master/dist/bundle.js#L34

Example project:
https://github.com/bodia-uz/rollup-postcss-modules-test

**Comment by bodia-uz** [comment]
Reason:

https://github.com/egoist/rollup-plugin-postcss/blob/beef7c55a4f848a419693b9c91a723e661618e6c/src/postcss-loader.js#L75-L77
+
https://github.com/ben-eb/cssnano/tree/master/packages/postcss-zindex

**Comment by egoist** [comment]
Should we set it by default?

**Comment by bodia-uz** [comment]
I think you should.
Or update to cssnano@4, when it ready, which use safe preset by default.
Unfortunately it still [RC](https://github.com/ben-eb/cssnano/releases).

**Comment by egoist** [comment]
I'm ok with setting it to `safe` by default, can you send a pull request (including its test cases too)?

**Comment by wardpeet** [comment]
Upgrading to cssnano@4 was done in https://github.com/egoist/rollup-plugin-postcss/pull/133
