### ISSUE TITLE
Add ~ alias for scss imports from node_modules

### ISSUE THREAD

**Issue by gustav-vidispine** [egoist/rollup-plugin-postcss#76]
Currently when you import a file via sass/scss you have to run 

`<style lang="scss" scoped>
@import 'node_modules/path/to/*.scss';
</style>`

In other bundlers (e.g. Poi with webpack) you have the alias ~ for node_modules. Would be nice to have this alias to this repo too for consistency when building with different environments (Poi/Webpack + Bili/Rollup).

**Comment by egoist** [comment]
Done https://github.com/egoist/rollup-plugin-postcss#imports
