### ISSUE TITLE
An @import loop has been found

### ISSUE THREAD

**Issue by raphaelokon** [egoist/rollup-plugin-postcss#78]
Hi there, 

I just noticed a regression in `v1.3.0` /w Rollup v0.56.3 on Node v8.9.4. Given a `main.scss` that imports other `.scss` files: when I run a `rollup` build I am getting the following message:

```scss
// main.scss
@import "./base";
```

```
[!] (postcss plugin) Error: An @import loop has been found:
    /src/styles/main.scss imports /src/styles/main.scss
```

Downgrading to `v1.2.9` works perfectly.

**Comment by egoist** [comment]
Fixed in `v1.3.1`
