### ISSUE TITLE
error on styleinject

### ISSUE THREAD

**Issue by CharlesKumar** [egoist/rollup-plugin-postcss#80]
Hi all,

I am new to rollup and postcss

I am getting this error even after rollup-plugin-node-resolve 

```

(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
olluplearn-rollup
ode_modulesstyle-injectdiststyle-inject.es.js (imported by src\styles\main.css)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
C:\Users\Charlie\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js (guessing 'styleInject')
created build/js/main.min.js in 936ms
```

This is my rollup.conig.js

```
import babel from "rollup-plugin-babel";
import eslint from "rollup-plugin-eslint";
import commonjs from "rollup-plugin-commonjs";
import resolve from "rollup-plugin-node-resolve";
import replace from "rollup-plugin-replace";
import uglify from "rollup-plugin-uglify";
import postcss from "rollup-plugin-postcss";
import simplevars from "postcss-simple-vars";
import nested from "postcss-nested";
import cssnext from "postcss-cssnext";
import cssnano from "cssnano";

export default {
  input: "src/scripts/main.js",
  output: {
    file: "build/js/main.min.js",
    format: "iife",
    sourcemap: process.env.NODE_ENV !== "production" ? false : "inline-map"
  },
  plugins: [
    eslint({ exclude: "src/styles/**" }),
    resolve({ jsnext: true, main: true, browser: true }),
    commonjs(),
    postcss({
      plugins: [
        simplevars(),
        nested(),
        cssnext({ warnForDuplicates: false }),
        cssnano()
      ],
      extensions: [".css"]
    }),
    replace({
      exclude: "node_modules/**",
      ENV: JSON.stringify(process.env.NODE_ENV || "development")
    }),
    babel({ exclude: "node_modules/**" }),
    process.env.NODE_ENV === "production" && uglify()
  ]
};
```

I am learning using this [tutorial](https://code.lengstorf.com/learn-rollup-css/) (may be outdated)

**Comment by egoist** [comment]
I've tested your setup and it works fine: https://gist.github.com/egoist/7460f76907edc8eea578154db8cc328a

**Comment by corumj** [comment]
I have the same issue, with the same tutorial.  Running  Node v8.9.3 on Windows 10 if that makes a difference, almost the same rollup.config.js - I removed some stuff to try to narrow it down so mine looks like this:

import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import postcss from 'rollup-plugin-postcss'

export default {
  input: 'src/scripts/main.js',
  output: {
    file: 'build/js/main.min.js',
    format: 'iife',
    name: 'react'
  },
  plugins: [
    postcss(),
    uglify(),
    resolve(),
    babel({
      exclude: 'node_modules/**' // only transpile our source code
    })
  ]
};

and my package.json looks like this:
{
  "name": "reactes6",
  "version": "1.0.0",
  "description": "This is the Real Time Electronic Area Canvassing Tool",
  "main": "build/js/main.min.js",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015-rollup": "^3.0.0",
    "rollup": "^0.56.3",
    "rollup-plugin-babel": "^3.0.3",
    "rollup-plugin-node-resolve": "^3.0.3",
    "rollup-plugin-postcss": "^1.3.1",
    "rollup-plugin-uglify": "^3.0.0"
  },
  "dependencies": {}
}

**Comment by egoist** [comment]
Can you confirm https://gist.github.com/egoist/7460f76907edc8eea578154db8cc328a this is working on windows or not? Might be related to some path issue.

**Comment by egoist** [comment]
I can confirm that now 😅https://ci.appveyor.com/project/egoist/rollup-plugin-postcss/build/1.0.2

**Comment by corumj** [comment]
So when I remove uglifyjs() I see that it's attempting to use the styleInject function but it never declares it anywhere but it is attempting to pass it in to the iife that rollup is creating - 

```
var react = (function (exports,styleInject) {
'use strict';

styleInject = styleInject && styleInject.hasOwnProperty('default') ? styleInject['default'] : styleInject;


var css = "*bunch of css*";
styleInject(css);
```

**Comment by egoist** [comment]
it fails because the path separator on windows is backslash, we need to convert it to slash at this line https://github.com/egoist/rollup-plugin-postcss/blob/268ecfe4da9d93d114b78da34194ba0d5e4c5a5f/src/postcss-loader.js#L8 😅
