### ISSUE TITLE
Cannot find `node-sass` in Yarn workspace

### ISSUE THREAD

**Issue by swansontec** [egoist/rollup-plugin-postcss#84]
I am using Yarn workspaces, which allows several projects to live in the same Git repository and share a common `node_modules` folder:

```
node_modules/
package.json
packages/
  some-library/
    package.json
    rollup.config.js
  another-library/
    package.json
    rollup.config.js
```

When I try to run rollup within `another-library`, the `rollup-plugin-postcss` plugin complains that it cannot find `packages/another-library/node_modules/node-scss`, which doesn't exist. This is because the `node_modules` directory isn't inside `another-library`, but two levels up from us.

## Possible Solutions

It looks like the `localRequire` function is to blame, since it is hard-coded to only look in the current working directory:

```js
const localRequire = name => require(path.resolve('node_modules', name))
```

One solution might be to have `localRequire` fall back on normal require if there's an issue:

```js
const localRequire = name => {
  try {
    return require(path.resolve('node_modules', name))
  } catch (e) {
    return require(name)
  }
}
```

This would be a quick & dirty fix. Otherwise, maybe just ditching `localRequire` and using normal `require` might work, on the grounds that `rollup-plugin-postcss` and `node-sass` should be installed to the same place anyhow. Another option is enhance `localRequire` using the `node-resolve` package, so it will accurately search for the `node_modules` directory starting in the current working directory.

**Comment by egoist** [comment]
We can use https://yarnpkg.com/zh-Hans/package/import-from

**Comment by swansontec** [comment]
Release 1.3.4 has the fix, so this is resolved now. Thanks a lot!
