### ISSUE TITLE
How to get one style tag?

### ISSUE THREAD

**Issue by btd** [egoist/rollup-plugin-postcss#9]
Currently if o use component way to define styles, i have one <style> per component, which is not very good. Is any way now to combine them all? If no, would you be ok if i create PR?

**Comment by egoist** [comment]
Yeah, I'd like to a PR for this, but in production we're more likely to extract css into a single file, so https://github.com/egoist/rollup-plugin-postcss/pull/7 needs help too 🌟

**Comment by meszaros-lajos-gyorgy** [comment]
Maybe you could try https://www.npmjs.com/package/postcss-import, which flattens the imports into a single output.

**Comment by egoist** [comment]
Hmm, now we have `combineStyleTags` and `extract` options, but I actually `combineStyleTags` should be used carefully since we don't always want to insert all styles once. It would be better to use `extract` option in production environment.
