### ISSUE TITLE
Have plans to support `.pcss` extension?

### ISSUE THREAD

**Issue by kubosho** [egoist/rollup-plugin-postcss#92]
PostCSS uses `.pcss` extension but this plugin not supported `.pcss` extension.
(I watched https://github.com/egoist/rollup-plugin-postcss/blob/240ec41/src/postcss-loader.js#L55 and https://github.com/egoist/rollup-plugin-postcss/blob/240ec41/src/postcss-loader.js#L61)

Have plans to support `.pcss` extension?

sources:

- https://twitter.com/PostCSS/status/661645290622083073
- https://twitter.com/PostCSS/status/935961939494227970
- https://github.com/github/linguist/pull/3916

**Comment by egoist** [comment]
Hmm I've never seen one use `.pcss` with PostCSS 🤔
