### ISSUE TITLE
Inject the whole CSS in a single style tag?

### ISSUE THREAD

**Issue by danburzo** [egoist/rollup-plugin-postcss#95]
Hi there,

I'm working on a React [component library](https://github.com/danburzo/uiuiui) whose build process I recently moved to Rollup. Since the CSS is split in many files, it currently generates an unsustainable amount of `<style>` tags in `<head>`. Is there a way to bundle them in a single style tag?

**Comment by egoist** [comment]
The best practice is to extract css into a single file.

**Comment by egoist** [comment]
> Is there a way to bundle them in a single style tag?

This is possible, we need to make [style-inject](https://github.com/egoist/style-inject) reuse the same `<style>` tag on every injection.

**Comment by danburzo** [comment]
Thanks for the info! I'll go with a single css file.
